# Generated by Django 4.2.30 on 2026-08-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Name (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Name (RU)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main branch', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('allowed_radius_meters', models.PositiveIntegerField(default=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Restaurant location',
                'verbose_name_plural': 'Restaurant locations',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Table number')),
                ('seats', models.PositiveSmallIntegerField(default=4, verbose_name='Seats')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Restaurant table',
                'verbose_name_plural': 'Restaurant tables',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=150, verbose_name='Name (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Name (RU)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, verbose_name='Description (UZ)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (RU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Photo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
